### ISSUE TITLE
Subdomain or URL path for FHIR endpoints

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-issues#40]
I saw an infrastructure tasks for identifying the URL prefixes for FHIR APIs,
that could be either the /fhir/ vs /hapi-fhir-jpaserver/fhir thing. We should answer that. I thought it was related to v5 or v6 of HAPI-FHIR. Can it be changed or standardized?

Regardless a DNS name for the server, after security measures are in place, would be nice for use in a connectathon.

**Comment by joeflack4** [comment]
Closing this as this will be somewhat handled by #119, although it could be though of as a subcomponent of that.

As of right now, the path is `/fhir/`, and we only have an R4 implementation.
