### ISSUE TITLE
Load Non-OWL terminologies into FHIR

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-issues#43]
HAPI has a LOINC loader. Does it also have one for SNOMED and ICD?
If so, desrcibe them and point to the doc.s here.
What about RxNorm and ATC?
Others? list them.

Detail on Google Docs: https://docs.google.com/document/d/1QwOKCCLYZAYmiOLiYMjxVChgN0EraObDQZTToNASK-E/edit

**Comment by joeflack4** [comment]
Rating ease really depends on which terminology we're talking about. For any that require transformations from their own custom format, that could take a bunch of time `ease 1`. Some of these are more standard, and HAPI even has loaders for them 

- S SNOMED 
- S LOINC
- S ICD
- S THO ?
-    others?
- L LOINC + comp-loinc axioms (ticket coming Monday) 
- RxNorm (edit, lesser licensing?)
- CPT (commercial licensing issues)

**Comment by chrisroederucdenver** [comment]
I added RxNorm to the list above, per Chris Chute.

**Comment by chrisroederucdenver** [comment]
We loaded what we need, many of these. Closing even though some that have not been loaded remain. We'll open more, more specific tix for those as needed.

**Comment by chrisroederucdenver** [comment]
Closing this broad list since we got what we needed. Some of these remain. WE'll open specific tix as necessary.
