### ISSUE TITLE
Easy HPO

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-issues#58]
Load HPO CodeSystem with pyrophen, add tests for checking it's loaded, test a few concepts.

**Related**
- #33
- #41
- [Old HPO issue](https://github.com/HOT-Ecosystem/hapi-fhir-jpaserver-starter/issues/1)

**Comment by joeflack4** [comment]
From what I understand, I would be using pyrophen to create an HPO CodeSystem JSON file, and then I would upload that to our TIMS server. Then I could do some testing.

In regards to "test against phenopackets work", I would need more information about that.

**Comment by chrisroederucdenver** [comment]
If you're using pyrophen, assume it works with phenopackets as they are both driven and mostly developed by Peter.

**Comment by joeflack4** [comment]
That makes sense, but I still don't know what to do. I assume there may be some demo phenopackets example files and I just need to do something with them? But I'm not sure what, or where to get them. I could check Peter's codebases to see if those phenopackets are there. But if this involves the server accepting a phenopacket resource, then this would be one of the most, if not the most, complex issues on our board (involves merging our codebase w/ peter's)

**Comment by chrisroederucdenver** [comment]
"assume it works with phenopackets" means don't sweat it.
There's a difference between an integration test which is what that really is and a unit test. Let's do as close to unit as we can, described below. I mentioned looking at integration with phenopackets, I think, in the case we were looking at alternatives to pyrophen.

Step-by-step (and forgive me if I go into too much detail, and I'm writing this from memory...)
- run pyrophen to create the json for loading into HAPI-FHIR
- load it into HAPI-FHIR
- do some kind of unit test to verify we loaded it even though at this point the load should say it succeeded.
That unit test would be an adaptation of stuff I have in the Jupyter notebook:
- does pyrophen show up in the ConceptSystem search (maybe not, it doesn't seem to be working right)? 
- does it show up if you search for it explicitly.
- open the json file and pick a few random concept ids and try to $lookup on those
That much should be good.

**Comment by joeflack4** [comment]
Ok, the steps you laid out jive with my understanding, that's good.

As for the phenopackets, I won't sweat it for the time being as you say. If that is not part of this issue though, maybe move it to the HPO hard issue or make it another issue.

**Comment by chrisroederucdenver** [comment]
I saw your list above, sorry for repeating it. You got it. I deleted the line in the first comment about testing against phenopackets. maybe move what to HPO-hard?

**Comment by joeflack4** [comment]
Ok, great. I was saying if the phenopackets bit is not part of this issue, maybe move it into another issue (e.g. HPO hard), but looks like you removed it from scope.

**Comment by chrisroederucdenver** [comment]
Looking at my fhir-owl work and what comes out of pyrophen, we need to deal with the colon vs underscore issue.

**Comment by chrisroederucdenver** [comment]
to be superseded by a proper owl import soon, if not already.
