### ISSUE TITLE
Closure: Computing Closure, Include ChrisM

### ISSUE THREAD

**Issue by chrisroederucdenver** [HOT-Ecosystem/hapi-issues#67]
from a comment by ChrisM on another ticket:

> Some ontology services like OLS will run an OWL reasoner to do a classification step in advance first, unless that ontology is configured otherwise. I think that is a bad idea but this is subject of ongoing discussion between myself, Nico, David OS, Jim, and others. If you don't do a classification step you are bound to run into some ontology that releases a version that hasn't been classified in advance. This is nuts imo but if you don't have a strategy in place then the ontology will look fragmented and flat. The best thing to do is say: this is not the wild west, there are some standards your owl must adhere to before we include it
> 
> The other reasoning use case is closures. If you want to include anatomy ontologies like uberon that don't use SNOMED SEP hacks then you likely want to support operations like "include all parts of the brain". You can approximate this by doing naive graph walking over a set of predicates but it's better to run relation-graph ahead of time to precompute the closure.

**Comment by joeflack4** [comment]
Closing this as we have been engaging Chris M much more often. This has culminated in an ultimate decision of whether or not to use OAK to do this and connect it to our HAPI server. Will be meeting this Monday and hopefully will have the final decision on that by the end of that day.
